## Put comments here that give an overall description of what your
## functions do



# makeCacheMatrix creates a special "matrix" object that can cache its inverse.

# it contains a list of functions to:
# set the values of the matrix
# get the values of the matrix
# set the values of the inverse
# get the values of the inverse

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
       t setinverse <- function(inverse) i <<- inverse
        getinverse <- function() i
        list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


# cacheSolve computes the inverse of the special "matrix" generated by the function makeCacheMatrix. 
# cacheSolve checks if the inverse has already been computed. 
# If yes, it takes the inverse from the cache, otherwise it calculates the inverse and saves it in the cache.

cacheSolve <- function(x, ...) {
        i <- x$getinverse()
        if(!is.null(i)) {
                message("getting cached inverse")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinverse(i)
        i
}
